// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwVqtFk-4WR0II4VjlMOYUHTY3gdE1MR8',
    appId: '1:821742761773:web:830618f5e863b0888f45a4',
    messagingSenderId: '821742761773',
    projectId: 'mobile-store-10fdd',
    authDomain: 'mobile-store-10fdd.firebaseapp.com',
    storageBucket: 'mobile-store-10fdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAASOmM-k7vLM16WoztwYk1ZO_pDQi_HjA',
    appId: '1:821742761773:android:e581fd242bc3f1bb8f45a4',
    messagingSenderId: '821742761773',
    projectId: 'mobile-store-10fdd',
    storageBucket: 'mobile-store-10fdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsUL2M_tH-kYcpZqEopk5G1KrHo14ERn8',
    appId: '1:821742761773:ios:58f82066d06842b28f45a4',
    messagingSenderId: '821742761773',
    projectId: 'mobile-store-10fdd',
    storageBucket: 'mobile-store-10fdd.appspot.com',
    iosClientId: '821742761773-oeknchom21ulid6j7ijbaaah7u5lgiuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsUL2M_tH-kYcpZqEopk5G1KrHo14ERn8',
    appId: '1:821742761773:ios:81e0b8467198c7218f45a4',
    messagingSenderId: '821742761773',
    projectId: 'mobile-store-10fdd',
    storageBucket: 'mobile-store-10fdd.appspot.com',
    iosClientId: '821742761773-copdv6e9uvq1jf5dflr3cql8u67t85st.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileStore.RunnerTests',
  );
}
